apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  type: NodePort
  selector:
    app: employee-attendance-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008